import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  X,
  Copy,
  CheckCheck,
  Loader2,
  Swords,
  BarChart2,
  Trophy,
  AlertTriangle,
  Target,
  MessageSquare,
  FileText,
} from 'lucide-react'
import { toast } from 'sonner'

interface WeeklyReportModalProps {
  isOpen: boolean
  report: string
  loading: boolean
  onClose: () => void
}

const SECTION_ICONS: Record<string, { icon: React.ComponentType<{ size?: number }>; color: string }> = {
  'BATTLE SUMMARY':    { icon: Swords,        color: '#5B57F0' },
  'STAT CHANGES':      { icon: BarChart2,     color: '#3B82F6' },
  'WINS':              { icon: Trophy,        color: '#F59E0B' },
  'WEAK POINTS':       { icon: AlertTriangle, color: '#EF4444' },
  'NEXT WEEK MISSION': { icon: Target,        color: '#10B981' },
  "COACH'S MESSAGE":   { icon: MessageSquare, color: '#EC4899' },
}

function parseReport(text: string) {
  if (!text) return []

  const lines = text.split('\n')
  const sections: Array<{ title: string; content: string; Icon: React.ComponentType<{ size?: number }>; color: string }> = []
  let currentTitle = ''
  let currentContent: string[] = []

  for (const line of lines) {
    const trimmed = line.trim()
    const sectionMatch = trimmed.match(/^(\d+\.\s+)?[^a-z]*([A-Z][A-Z\s']+[A-Z])\s*(—.*)?$/)
    const matchedKey = sectionMatch
      ? Object.keys(SECTION_ICONS).find((k) => sectionMatch[2]?.includes(k))
      : undefined

    if (matchedKey) {
      if (currentTitle) {
        const meta = SECTION_ICONS[currentTitle] ?? { icon: FileText, color: '#5B57F0' }
        sections.push({
          title: currentTitle,
          content: currentContent.join('\n').trim(),
          Icon: meta.icon,
          color: meta.color,
        })
      }
      currentTitle = matchedKey
      currentContent = []
    } else if (currentTitle && trimmed) {
      currentContent.push(trimmed)
    }
  }

  if (currentTitle) {
    const meta = SECTION_ICONS[currentTitle] ?? { icon: FileText, color: '#5B57F0' }
    sections.push({
      title: currentTitle,
      content: currentContent.join('\n').trim(),
      Icon: meta.icon,
      color: meta.color,
    })
  }

  return sections
}

export default function WeeklyReportModal({
  isOpen,
  report,
  loading,
  onClose,
}: WeeklyReportModalProps) {
  const [copied, setCopied] = useState(false)

  const sections = parseReport(report)

  async function handleCopy() {
    await navigator.clipboard.writeText(report)
    setCopied(true)
    toast.success('Report copied to clipboard!')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
          <motion.div
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="w-full max-w-2xl max-h-[90vh] flex flex-col rounded-3xl overflow-hidden bg-white border border-[#EAE6DD] shadow-2xl"
          >
            {/* Header */}
            <div
              className="flex items-center justify-between px-6 py-4 border-b border-[#EAE6DD] bg-[#FAF8F5] flex-shrink-0"
            >
              <div className="flex items-center gap-3">
                <div
                  className="w-10 h-10 rounded-2xl flex items-center justify-center flex-shrink-0 bg-purple-50 border border-purple-200 text-[#5B57F0]"
                >
                  <FileText size={20} />
                </div>
                <div>
                  <h2
                    className="text-lg font-bold text-[#232019]"
                  >
                    Weekly RPG Report
                  </h2>
                  <p className="text-xs text-[#6E6A61]">
                    Generated by your AI Coach
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-xl text-[#8A857A] hover:bg-[#EAE6DD]/50 hover:text-[#232019] transition-colors cursor-pointer"
              >
                <X size={20} />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6 bg-[#FBFAF7]">
              {loading ? (
                <div className="flex flex-col items-center justify-center py-16 gap-4">
                  <Loader2 size={36} className="animate-spin text-[#5B57F0]" />
                  <p className="font-bold text-[#232019]">
                    Generating your weekly report...
                  </p>
                  <p className="text-xs text-[#8A857A]">
                    The AI Coach is analyzing your quest progress
                  </p>
                </div>
              ) : sections.length > 0 ? (
                <div className="space-y-4">
                  {sections.map((section, i) => (
                    <motion.div
                      key={section.title}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.08 }}
                      className="rounded-2xl p-5 bg-white border border-[#EAE6DD] shadow-xs"
                      style={{
                        borderLeft: `4px solid ${section.color}`,
                      }}
                    >
                      <div className="flex items-center gap-2.5 mb-3">
                        <div
                          className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 shadow-2xs"
                          style={{ background: `${section.color}15`, color: section.color }}
                        >
                          <section.Icon size={15} />
                        </div>
                        <h3
                          className="font-bold text-xs uppercase tracking-wider"
                          style={{ color: section.color }}
                        >
                          {section.title}
                        </h3>
                      </div>
                      <p
                        className="text-sm leading-relaxed whitespace-pre-line text-[#232019]"
                      >
                        {section.content}
                      </p>
                    </motion.div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <div
                    className="w-14 h-14 rounded-2xl flex items-center justify-center mx-auto mb-3 bg-[#FAF8F5] border border-[#EAE6DD]"
                  >
                    <FileText size={24} className="text-[#8A857A]" />
                  </div>
                  <p className="text-sm text-[#8A857A]">No report generated yet.</p>
                </div>
              )}
            </div>

            {/* Footer */}
            {!loading && report && (
              <div
                className="px-6 py-4 border-t border-[#EAE6DD] bg-white flex items-center justify-between flex-shrink-0"
              >
                <p className="text-xs text-[#8A857A]">
                  Week of {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric' })}
                </p>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl font-semibold text-sm transition-all duration-200 bg-purple-50 text-[#5B57F0] border border-purple-200 hover:bg-[#5B57F0] hover:text-white cursor-pointer shadow-xs"
                >
                  {copied ? <CheckCheck size={15} /> : <Copy size={15} />}
                  {copied ? 'Copied!' : 'Copy Report'}
                </button>
              </div>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
