'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { X, Copy, CheckCheck, Loader2 } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'

interface WeeklyReportModalProps {
  isOpen: boolean
  report: string
  loading: boolean
  onClose: () => void
}

const SECTION_ICONS: Record<string, { icon: string; color: string }> = {
  'BATTLE SUMMARY': { icon: '⚔️', color: '#7C3AED' },
  'STAT CHANGES':   { icon: '📊', color: '#3B82F6' },
  'WINS':           { icon: '🏆', color: '#F59E0B' },
  'WEAK POINTS':    { icon: '⚠️', color: '#EF4444' },
  'NEXT WEEK MISSION': { icon: '🎯', color: '#22C55E' },
  "COACH'S MESSAGE": { icon: '💬', color: '#EC4899' },
}

function parseReport(text: string) {
  if (!text) return []

  const lines = text.split('\n')
  const sections: Array<{ title: string; content: string; icon: string; color: string }> = []
  let currentTitle = ''
  let currentContent: string[] = []

  for (const line of lines) {
    const trimmed = line.trim()
    // Match lines like "1. ⚔️ BATTLE SUMMARY — ..." or "⚔️ BATTLE SUMMARY"
    const sectionMatch = trimmed.match(/^(\d+\.\s+)?[^a-z]*([A-Z][A-Z\s']+[A-Z])\s*(—.*)?$/)
    const matchedKey = sectionMatch
      ? Object.keys(SECTION_ICONS).find((k) => sectionMatch[2]?.includes(k))
      : undefined

    if (matchedKey) {
      if (currentTitle) {
        const meta = SECTION_ICONS[currentTitle] ?? { icon: '📌', color: '#7C3AED' }
        sections.push({
          title: currentTitle,
          content: currentContent.join('\n').trim(),
          icon: meta.icon,
          color: meta.color,
        })
      }
      currentTitle = matchedKey
      currentContent = []
    } else if (currentTitle && trimmed) {
      currentContent.push(trimmed)
    }
  }

  if (currentTitle) {
    const meta = SECTION_ICONS[currentTitle] ?? { icon: '📌', color: '#7C3AED' }
    sections.push({
      title: currentTitle,
      content: currentContent.join('\n').trim(),
      icon: meta.icon,
      color: meta.color,
    })
  }

  return sections
}

export default function WeeklyReportModal({
  isOpen,
  report,
  loading,
  onClose,
}: WeeklyReportModalProps) {
  const [copied, setCopied] = useState(false)

  const sections = parseReport(report)

  async function handleCopy() {
    await navigator.clipboard.writeText(report)
    setCopied(true)
    toast.success('Report copied to clipboard!')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <motion.div
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="w-full max-w-2xl max-h-[90vh] flex flex-col rounded-2xl overflow-hidden"
            style={{ background: '#13131F', border: '1px solid #7C3AED44' }}
          >
            {/* Header */}
            <div
              className="flex items-center justify-between px-6 py-4 border-b flex-shrink-0"
              style={{ borderColor: '#1E1E35' }}
            >
              <div className="flex items-center gap-3">
                <span className="text-2xl">📜</span>
                <div>
                  <h2
                    className="text-xl font-bold"
                    style={{ fontFamily: 'Oxanium, sans-serif', color: '#F1F0FF' }}
                  >
                    Weekly RPG Report
                  </h2>
                  <p className="text-xs" style={{ color: '#5C5A7A' }}>
                    Generated by your AI Coach
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-lg transition-colors"
                style={{ color: '#5C5A7A' }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = '#1E1E35'
                  e.currentTarget.style.color = '#F1F0FF'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'transparent'
                  e.currentTarget.style.color = '#5C5A7A'
                }}
              >
                <X size={20} />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-6">
              {loading ? (
                <div className="flex flex-col items-center justify-center py-16 gap-4">
                  <Loader2 size={40} className="animate-spin" style={{ color: '#7C3AED' }} />
                  <p style={{ fontFamily: 'Oxanium, sans-serif', color: '#9B99B8' }}>
                    Generating your weekly report...
                  </p>
                  <p className="text-xs" style={{ color: '#5C5A7A' }}>
                    The AI Coach is analyzing your battle log
                  </p>
                </div>
              ) : sections.length > 0 ? (
                <div className="space-y-5">
                  {sections.map((section, i) => (
                    <motion.div
                      key={section.title}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: i * 0.08 }}
                      className="rounded-xl p-5"
                      style={{
                        background: '#0F0F1A',
                        border: `1px solid ${section.color}33`,
                        borderLeft: `3px solid ${section.color}`,
                      }}
                    >
                      <div className="flex items-center gap-2 mb-3">
                        <span className="text-xl">{section.icon}</span>
                        <h3
                          className="font-bold text-sm uppercase tracking-wider"
                          style={{ fontFamily: 'Oxanium, sans-serif', color: section.color }}
                        >
                          {section.title}
                        </h3>
                      </div>
                      <p
                        className="text-sm leading-relaxed whitespace-pre-line"
                        style={{ color: '#C4C2D8' }}
                      >
                        {section.content}
                      </p>
                    </motion.div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <div className="text-4xl mb-3">📜</div>
                  <p style={{ color: '#5C5A7A' }}>No report generated yet.</p>
                </div>
              )}
            </div>

            {/* Footer */}
            {!loading && report && (
              <div
                className="px-6 py-4 border-t flex items-center justify-between flex-shrink-0"
                style={{ borderColor: '#1E1E35' }}
              >
                <p className="text-xs" style={{ color: '#5C5A7A' }}>
                  Week of {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric' })}
                </p>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg font-medium text-sm transition-all duration-200"
                  style={{
                    background: copied ? '#22C55E22' : '#7C3AED22',
                    color: copied ? '#22C55E' : '#9F67FF',
                    border: `1px solid ${copied ? '#22C55E44' : '#7C3AED44'}`,
                  }}
                >
                  {copied ? <CheckCheck size={15} /> : <Copy size={15} />}
                  {copied ? 'Copied!' : 'Copy Report'}
                </button>
              </div>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
