import React from 'react'
import {
  Swords,
  Dumbbell,
  Brain,
  Sparkles,
  Heart,
  Coins,
  MessageSquare,
  Flame,
  Zap,
  Trophy,
  Target,
  BookOpen,
  Crown,
  Activity,
  Smile,
  Frown,
  Meh,
  Laugh,
  Users,
  HeartHandshake,
  Shield,
  Star,
  Lock,
  Unlock,
  Calendar,
  BarChart3,
  TrendingUp,
  Settings,
  Bot,
  Skull,
  Timer,
  Check,
  X,
  Compass,
  Palette,
  Code,
  Music,
  Footprints,
  Lightbulb,
  Droplets,
  Moon,
  Sun,
  Building2,
  FileText,
  AlertTriangle,
  Ghost,
  Rocket,
  Award,
  Crosshair,
  Globe,
  Wrench,
  ShieldAlert,
  Ban,
  CheckCircle2,
  UserPlus,
  Mountain,
  Wind,
  GraduationCap,
  Eye,
  PartyPopper,
  Flame as Fire,
  Gem,
  LucideProps,
} from 'lucide-react'

export const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Stat / Attribute Icons
  str: Dumbbell,
  int: Brain,
  wis: Sparkles,
  vit: Heart,
  gold: Coins,
  cha: MessageSquare,

  // General RPG & Feature Icons
  swords: Swords,
  sword: Swords,
  dumbbell: Dumbbell,
  fitness: Dumbbell,
  workout: Dumbbell,
  brain: Brain,
  mind: Brain,
  sparkles: Sparkles,
  wisdom: Sparkles,
  heart: Heart,
  health: Heart,
  coins: Coins,
  wealth: Coins,
  message: MessageSquare,
  chat: MessageSquare,
  social: MessageSquare,
  flame: Flame,
  fire: Flame,
  zap: Zap,
  energy: Zap,
  speed: Zap,
  trophy: Trophy,
  achievement: Trophy,
  target: Target,
  goal: Target,
  book: BookOpen,
  study: BookOpen,
  crown: Crown,
  legendary: Crown,
  activity: Activity,
  agility: Activity,
  shield: Shield,
  defense: Shield,
  star: Star,
  lock: Lock,
  unlock: Unlock,
  calendar: Calendar,
  chart: BarChart3,
  trend: TrendingUp,
  settings: Settings,
  bot: Bot,
  ai: Bot,
  skull: Skull,
  timer: Timer,
  check: Check,
  close: X,
  users: Users,
  party: Users,
  friends: Users,
  couple: HeartHandshake,
  family: Users,
  compass: Compass,
  palette: Palette,
  art: Palette,
  code: Code,
  dev: Code,
  music: Music,
  footprints: Footprints,
  walk: Footprints,
  run: Activity,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  droplets: Droplets,
  water: Droplets,
  moon: Moon,
  sun: Sun,
  bank: Building2,
  doc: FileText,
  warning: AlertTriangle,
  ghost: Ghost,
  rocket: Rocket,
  award: Award,
  crosshair: Crosshair,
  globe: Globe,
  wrench: Wrench,
  shieldalert: ShieldAlert,
  ban: Ban,
  checkcircle: CheckCircle2,
  userplus: UserPlus,
  mountain: Mountain,
  wind: Wind,
  graduation: GraduationCap,
  gem: Gem,
  diamond: Gem,
  party_popper: PartyPopper,
  eye: Eye,

  // Avatar Options
  wizard: Sparkles,
  archer: Target,
  crystal: Sparkles,
  dragon: Flame,
  lion: Crown,
  wolf: Moon,
  eagle: Wind,
  night: Moon,

  // Boss Keys
  demon: Skull,
  monster: Ghost,
  invader: Bot,
  alien: Bot,
  volcano: Flame,
  scorpion: Skull,

  // Emoji to Lucide mappings (for backwards compatibility with existing database rows)
  '💪': Dumbbell,
  '🧠': Brain,
  '🧘': Sparkles,
  '❤️': Heart,
  '💰': Coins,
  '🗣️': MessageSquare,
  '🗣': MessageSquare,
  '🔥': Flame,
  '⚡': Zap,
  '🏆': Trophy,
  '🎯': Target,
  '📚': BookOpen,
  '👑': Crown,
  '✨': Sparkles,
  '🌟': Star,
  '💎': Gem,
  '⚔️': Swords,
  '⚔': Swords,
  '🛡️': Shield,
  '🛡': Shield,
  '🏃': Activity,
  '🏋️': Dumbbell,
  '🏋': Dumbbell,
  '🚶': Footprints,
  '💡': Lightbulb,
  '💧': Droplets,
  '🥗': Heart,
  '😴': Moon,
  '🏦': Building2,
  '📝': FileText,
  '📖': BookOpen,
  '📓': FileText,
  '📈': TrendingUp,
  '📊': BarChart3,
  '🤝': HeartHandshake,
  '💬': MessageSquare,
  '👀': Eye,
  '🌱': Activity,
  '🕯️': Sparkles,
  '🕯': Sparkles,
  '☮️': Sparkles,
  '☮': Sparkles,
  '🔭': Compass,
  '🔒': Lock,
  '👥': Users,
  '💑': HeartHandshake,
  '👨‍👩‍👧': Users,
  '🤖': Bot,
  '😈': Skull,
  '💀': Skull,
  '🔮': Sparkles,
  '🎉': PartyPopper,
  '📋': FileText,
  '🧙': Sparkles,
  '🏹': Target,
  '🦅': Wind,
  '🐉': Flame,
  '🦁': Crown,
  '🐺': Moon,
  '🌙': Moon,
  '☀️': Sun,
  '🌊': Droplets,
  '🎨': Palette,
  '💻': Code,
  '🎵': Music,
  '🧪': Activity,
  '🎮': Sparkles,
  '🚀': Rocket,
  '😔': Frown,
  '😐': Meh,
  '🙂': Smile,
  '😊': Laugh,
  '😍': Heart,
  '👹': Skull,
  '👾': Bot,
  '☠️': Skull,
  '☠': Skull,
  '🦂': Skull,
  '🌋': Mountain,
  '🏔️': Mountain,
  '🏔': Mountain,
  '🌅': Sun,
  '🦉': Moon,
  '🌪️': Wind,
  '🌪': Wind,
  '⚙️': Settings,
  '⚙': Settings,
  '🗺️': Compass,
  '🗺': Compass,
  '🚫': Ban,
  '⚠️': AlertTriangle,
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🥇': Trophy,
  '🥈': Award,
  '🥉': Award,
  '✅': CheckCircle2,
  '📥': FileText,
  '📤': FileText,
}

interface DynamicIconProps extends LucideProps {
  name?: string
  fallback?: React.ComponentType<LucideProps>
}

export function DynamicIcon({ name, fallback: Fallback = Sparkles, ...props }: DynamicIconProps) {
  if (!name) return <Fallback {...props} />
  const normalizedKey = name.toLowerCase().trim()
  const IconComponent = ICON_MAP[name] || ICON_MAP[normalizedKey] || Fallback
  return <IconComponent {...props} />
}

export default DynamicIcon
